<%@ page contentType="text/html; charset=big5" language="java" import="java.sql.*" errorPage="" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=big5" />
<title>無標題文件</title>
</head>

<body>
<div id="subheader">
  <h2>PLEASE READ THESE TERMS OF USE CAREFULLY AS  THEY CONTAIN IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS,  REMEDIES AND OBLIGATIONS AND SET FORTH VARIOUS LIMITATIONS AND  EXCLUSIONS THERETO, INCLUDING WITHOUT LIMITATION A DISPUTE RESOLUTION  CLAUSE THAT GOVERNS HOW DISPUTES WILL BE RESOLVED.</h2>
</div>
<div id="content">
  <div>
    <p>Welcome to IIS, a social utility that  connects you with the people around you. The IIS service and  network (collectively, &quot;IIS&quot; or &quot;the Service&quot;) are operated by  IIS, Inc. and its corporate affiliates (collectively, &quot;us&quot;, &quot;we&quot;  or &quot;the Company&quot;). By accessing or using our web site at  www.IIS.com or the mobile version thereof (together the &quot;Site&quot;) or  by posting a Share Button on your site, you (the &quot;User&quot;) signify that  you have read, understand and agree to be bound by these Terms of Use  (&quot;Terms of Use&quot; or &quot;Agreement&quot;), whether or not you are a registered  member of IIS. We reserve the right, at our sole discretion, to  change, modify, add, or delete portions of these Terms of Use at any  time without further notice. If we do this, we will post the changes to  these Terms of Use on this page and will indicate at the top of this  page the date these terms were last revised. Your continued use of the  Service or the Site after any such changes constitutes your acceptance  of the new Terms of Use. If you do not agree to abide by these or any  future Terms of Use, do not use or access (or continue to use or  access) the Service or the Site. It is your responsibility to regularly  check the Site to determine if there have been changes to these Terms  of Use and to review such changes.</p>
    <h2>Eligibility</h2>
    <p> Membership in the Service is void where prohibited. This Site is  intended solely for Users who are thirteen (13) years of age or older,  and any registration by, use of or access to the Site by anyone under  13 is unauthorized, unlicensed and in violation of these Terms of Use.  By using the Service or the Site, you represent and warrant that you  are 13 or older and that you agree to and to abide by all of the terms  and conditions of this Agreement. The Company may terminate your  membership, delete your profile and any content or information that you  have posted on the Site and/or prohibit you from using or accessing the  Service or the Site (or any portion, aspect or feature of the Service  or the Site) for any reason, at any time in its sole discretion, with  or without notice, including without limitation if it believes that you  are under 13.</p>
    <h2>Registration Data; Account Security</h2>
    <p>In  consideration of your use of the Site, you agree to (a) provide  accurate, current and complete information about you as may be prompted  by any registration forms on the Site (&quot;Registration Data&quot;); (b)  maintain the security of your password and identification; (c) maintain  and promptly update the Registration Data, and any other information  you provide to Company, to keep it accurate, current and complete; and  (d) be fully responsible for all use of your account and for any  actions that take place using your account.</p>
    <h2>Proprietary Rights in Site Content; Limited License</h2>
    <p>All  content on the Web site, including but not limited to designs, text,  graphics, pictures, video, information, software, music, sound and  other files, and their selection and arrangement (the &quot;Site Content&quot;),  are the proprietary property of the Company, its Users or its licensors  with all rights reserved. No Site Content may be modified, copied,  distributed, framed, reproduced, republished, downloaded, displayed,  posted, transmitted, or sold in any form or by any means, in whole or  in part, without the Company's prior written permission, except that  the foregoing does not apply to your own User Content (as defined  below) that you legally post on the Site. Provided that you are  eligible for use of the Site, you are granted a limited license to  access and use the Site and to download or print a copy of any portion  of the Site Content solely for your personal, non-commercial use,  provided that you keep all copyright or other proprietary notices  intact. Except for your own User Content, you may not republish Site  Content on any Internet, Intranet or Extranet site or incorporate the  information in any other database or compilation, and any other use of  the Site Content is strictly prohibited. Such license is subject to  these Site Terms and does not include use of any data mining, robots or  similar data gathering or extraction methods. Any use of the Site or  the Site Content other than as specifically authorized herein, without  the prior written permission of Company, is strictly prohibited and  will terminate the license granted herein. Such unauthorized use may  also violate applicable laws including without limitation copyright and  trademark laws and applicable communications regulations and statutes.  Unless explicitly stated herein, nothing in these Site Terms shall be  construed as conferring any license to intellectual property rights,  whether by estoppel, implication or otherwise. This license is  revocable at any time without notice and with or without cause.</p>
    <h2>Trademarks</h2>
    <p>32665,  IIS, THE IIS, IISHIGH, FBOOK, POKE, THE WALL and other  Company graphics, logos, designs, page headers, button icons, scripts  and service names are registered trademarks, trademarks or trade dress  of Company in the U.S. and/or other countries. Company's trademarks and  trade dress may not be used, including as part of trademarks and/or as  part of domain names, in connection with any product or service in any  manner that is likely to cause confusion and may not be copied,  imitated, or used, in whole or in part, without the prior written  permission of the Company. </p>
    <h2>User Conduct</h2>
    <p>You understand  that except for self-service advertising programs offered by us on the  Site (e.g., IIS Flyers), the Service and the Site are available  for your personal, non-commercial use only. You represent, warrant and  agree that no materials of any kind submitted through your account or  otherwise posted or shared by you through the Service will violate or  infringe upon the rights of any third party, including copyright,  trademark, privacy, publicity or other personal or proprietary rights;  or contain libelous, defamatory or otherwise unlawful material. You  further agree not to harvest or collect email addresses or other  contact information of Users from the Service or the Site by electronic  or other means for the purposes of sending unsolicited emails or other  unsolicited communications. Additionally, you agree not to use  automated scripts to collect information from the Service or the Site  or for any other purpose. You further agree that you may not use the  Service or the Site in any unlawful manner or in any other manner that  could damage, disable, overburden or impair the Site. In addition, you  agree not to use the Service or the Site to: </p>
    <ul>
      <li>upload, post,  transmit, share, store or otherwise make available any content that we  deem to be harmful, threatening, unlawful, defamatory, infringing,  abusive, inflammatory, harassing, vulgar, obscene, fraudulent, invasive  of privacy or publicity rights, hateful, or racially, ethnically or  otherwise objectionable; </li>
      <li>register for more than one User  account, register for a User account on behalf of an individual other  than yourself, or register for a User account on behalf of any group or  entity;</li>
      <li>impersonate any person or entity, or falsely state or  otherwise misrepresent yourself, your age or your affiliation with any  person or entity; </li>
      <li>upload, post, transmit, share or otherwise  make available any unsolicited or unauthorized advertising,  solicitations, promotional materials, &quot;junk mail,&quot; &quot;spam,&quot; &quot;chain  letters,&quot; &quot;pyramid schemes,&quot; or any other form of solicitation; </li>
      <li>upload,  post, transmit, share, store or otherwise make publicly available on  the Site any private information of any third party, including, without  limitation, addresses, phone numbers, email addresses, Social Security  numbers and credit card numbers;</li>
      <li>solicit personal information  from anyone under 18 or solicit passwords or personally identifying  information for commercial or unlawful purposes;</li>
      <li>upload, post,  transmit, share or otherwise make available any material that contains  software viruses or any other computer code, files or programs designed  to interrupt, destroy or limit the functionality of any computer  software or hardware or telecommunications equipment; </li>
      <li>intimidate or harass another; </li>
      <li>upload,  post, transmit, share, store or otherwise make available content that  would constitute, encourage or provide instructions for a criminal  offense, violate the rights of any party, or that would otherwise  create liability or violate any local, state, national or international  law;</li>
      <li>use or attempt to use another's account, service or system  without authorization from the Company, or create a false identity on  the Service or the Site.</li>
      <li>upload, post, transmit, share, store  or otherwise make available content that, in the sole judgment of  Company, is objectionable or which restricts or inhibits any other  person from using or enjoying the Site, or which may expose Company or  its Users to any harm or liability of any type.</li>
    </ul>
    <h2>User Content Posted on the Site</h2>
    <p>You  are solely responsible for the photos, profiles, messages, notes, text,  information, music, video, advertisements and other content that you  upload, publish or display (hereinafter, &quot;post&quot;) on or through the  Service or the Site, or transmit to or share with other Users  (collectively the &quot;User Content&quot;). You understand and agree that the  Company may, but is not obligated to, review and delete or remove  (without notice) any User Content in its sole discretion, including  without limitation User Content that in the sole judgment of the  Company violate this Agreement or which might be offensive, illegal, or  that might violate the rights, harm, or threaten the safety of Users or  others. <br />
        <br />
      By posting User Content to any part of the Site, you automatically  grant, and you represent and warrant that you have the right to grant,  to the Company an irrevocable, perpetual, non-exclusive, transferable,  fully paid, worldwide license (with the right to sublicense) to use,  copy, publicly perform, publicly display, reformat, translate, excerpt  (in whole or in part) and distribute such User Content for any purpose  on or in connection with the Site or the promotion thereof, to prepare  derivative works of, or incorporate into other works, such User  Content, and to grant and authorize sublicenses of the foregoing. You  may remove your User Content from the Site at any time. If you choose  to remove your User Content, the license granted above will  automatically expire.</p>
    <h2> IIS Mobile Services</h2>
    <p>The  Service includes certain services that are available via your mobile  phone, including (i) the ability to upload content to IIS via your  mobile phone (Mobile Uploads), (ii) the ability to receive and reply to  IIS messages, to poke and receive pokes and to write wall posts  using text messaging (Mobile Texts) and (iii) the ability to browse  IIS from your mobile phone (Mobile Web) (collectively the &quot;Mobile  Services&quot;). We do not charge for these Mobile Services. However, your  carrier's normal messaging, data and other rates and fees will still  apply. You should check with your carrier to find out what plans are  available and how much they cost. By using the Mobile Services, you  agree that we may communicate with you regarding IIS and its  partners by SMS, MMS, text message or other electronic means to your  mobile device and that certain information about your usage of the  Mobile Services may be communicated to us. </p>
    <h2>Copyright Complaints</h2>
    <p>If  you believe that any material on the Site infringes upon any copyright  which you own or control, you may send a written notification of such  infringement to our Designated Agent as set forth below: <br />
        <br />
      Name of Agent Designated to Receive Notification of Claimed Infringement:  Rudy Gadre <br />
      Full Address of Designated Agent to Which Notification Should be Sent: 156 University Ave., Suite 300, Palo Alto, CA 94301 <br />
      Telephone Number of Designated Agent: (650) 543-4800 <br />
      Facsimile Number of Designated Agent: (650) 543-4801 <br />
      E-Mail Address of Designated Agent:     copyright@IIS.com <br />
        <br />
      To meet the notice requirements under the Digital Millennium  Copyright Act, the notification must be a written communication that  includes the following: <br />
      <br />
      A. A physical or electronic signature of a person authorized  to act on behalf of the owner of an exclusive right that is allegedly  infringed; <br />
      <br />
      B. Identification of the copyrighted work claimed to have  been infringed, or, if multiple copyrighted works at a single online  site are covered by a single notification, a representative list of  such works at that site; <br />
      <br />
      C. Identification of the material that is claimed to be  infringing or to be the subject of infringing activity and that is to  be removed or access to which is to be disabled, and information  reasonably sufficient to permit us to locate the material; <br />
      <br />
      D. Information reasonably sufficient to permit us to contact  the complaining party, such as an address, telephone number and, if  available, an electronic mail address at which the complaining party  may be contacted; <br />
      <br />
      E. A statement that the complaining party has a good-faith  belief that use of the material in the manner complained of is not  authorized by the copyright owner, its agent or the law; and <br />
      <br />
      F. A statement that the information in the notification is  accurate, and under penalty of perjury, that the complaining party is  authorized to act on behalf of the owner of an exclusive right that is  allegedly infringed.</p>
    <h2>Repeat Infringer Policy</h2>
    <p>In  accordance with the Digital Millennium Copyright Act (DMCA) and other  applicable law, Company has adopted a policy of terminating, in  appropriate circumstances and at Company's sole discretion, members who  are deemed to be repeat infringers. Company may also at its sole  discretion limit access to the Site and/or terminate the memberships of  any Users who infringe any intellectual property rights of others,  whether or not there is any repeat infringement.</p>
    <h2>Links to Other Websites and Content</h2>
    <p>The  Site contains (or you may be sent through the Site or the Services)  links to other web sites (&quot;Third Party Sites&quot;) as well as articles,  photographs, text, graphics, pictures, designs, music, sound, video,  information, software and other content belonging to or originating  from third parties (the &quot;Third Party Content&quot;). Such Third Party Sites  and Third Party Content are not investigated, monitored or checked for  accuracy, appropriateness, or completeness by us, and we are not  responsible for any Third Party Sites accessed through the Site or any  Third Party Content posted on the Site, including without limitation  the content, accuracy, offensiveness, opinions, reliability or policies  of or contained in the Third Party Sites or the Third Party Content.  Inclusion of or linking to any Third Party Site or any Third Party  Content does not imply approval or endorsement thereof by us. If you  decide to leave the Site and access the Third Party Sites, you do so at  your own risk and you should be aware that our terms and policies no  longer govern. You should review the applicable terms and policies,  including privacy and data gathering practices, of any site to which  you navigate from the Site. </p>
    <h2>Share Service</h2>
    <p>Company  offers a feature whereby Users of the Site can share with others or  post to their own member profile, videos, articles and other Third  Party Content from, and/or links to, Third Party Sites through the  Service (the &quot;Share Service&quot;). You acknowledge and agree that your use  of the Share Services and all links, User Content or Third Party  Content shared through the Share Service is subject to, and will fully  comply with the User conduct rules set forth above and the other terms  and conditions set forth in these Terms of Use.</p>
    <h2>Use of Share Links by Online Content Providers</h2>
    <p>Subject  to the terms and conditions of these Terms of Use, Third Party Sites  that meet the requirements set forth below may place a Share Link (as  described below), in the form approved by Company, on pages of their  web sites to facilitate use of the Share Service. A Third Party Site  that posts a Share Link on its web site is referred to herein as an  &quot;Online Content Provider&quot; and shall abide and be subject to the  applicable sections of these Terms of Use. A &quot;Share Link&quot; is a button  and/or a text link appearing on an Online Content Provider's web page  that, upon being clicked by a User, enables us to launch a sharing  mechanism through which Users can share with others or post to their  own member profile, links and content from that page. <br />
        <br />
      In the event that the Share Link is a button that contains any  icons or other graphic images, trademarks or other proprietary  materials of Company, Online Content Provider is granted permission to  use such images, trademarks or other materials solely for the purpose  of placing the Share Link on Online Content Provider's site and solely  in the current form provided by the Company. In the event that the  Share Link is a text link, it must include the word &quot;IIS&quot; as part  of the link. The rights granted in this paragraph may be revoked by  Company at any time with or without cause in its sole discretion, and  upon such termination, Online Content Provider agree to immediately  remove all Share Links from its site. <br />
        <br />
      In order for an Online Content Provider to include a Share Link on  its pages, the Third Party Site must not contain any web content that  if shared or posted by a User would be a violation of the User conduct  rules set forth above. Without limiting the forgoing, Online Content  Provider agrees not to post a Share Link on any web site that contains,  and represents and warrants that such web site does not and will not  contain, any content that is infringing, harmful, threatening,  unlawful, defamatory, abusive, inflammatory, harassing, vulgar,  obscene, lewd, fraudulent, or invasive of privacy or publicity rights  or that may expose Company or its Users to any harm or liability of any  type. Upon including of a Share Link, Online Content Provider agrees to  defend, indemnify and hold Company, its subsidiaries and affiliates,  and each of their directors, officers, agents, contractors, partners  and employees, harmless from and against any loss, liability, claim,  demand, damages, costs and expenses, including reasonable attorney's  fees, arising out of or in connection with such Share Link, any links,  content or other items or materials which may be shared or posted  through such Share Link, or any breach or alleged breach of the  foregoing representations and warranties. <br />
        <br />
      By including a Share Link, Online Content Provider automatically  grants, and represents and warrants that it has the right to grant, to  the Company an irrevocable, perpetual, non-exclusive, transferable,  fully paid, worldwide license (with the right to sublicense) to use the  Share Service in order to link to, use, copy, publish, stream, publicly  perform, publicly display, reformat, translate, excerpt (in whole or in  part), summarize, and distribute the content, links and other materials  of any kind residing on any web pages on which Online Content Provider  places the Share Link.</p>
    <h2>User Disputes</h2>
    <p>You  are solely responsible for your interactions with other IIS Users.  We reserve the right, but have no obligation, to monitor disputes  between you and other Users.</p>
    <h2>Privacy</h2>
    <p>We care about the privacy of our Users. Click <a href="http://www.facebook.com/policy.php">here</a> to view the Site's Privacy Policy. By using the Site or the Service,  you are consenting to have your personal data transferred to and  processed in the United States.</p>
    <h2>Disclaimers</h2>
    <p>The Company  is not responsible or liable in any manner for any User Content or  Third Party Content posted on the Site or in connection with the  Service, whether posted or caused by Users of the Site or by any of the  equipment or programming associated with or utilized in the Site or the  Service. Although we provide rules for User conduct and postings, we do  not control and are not responsible for what Users post on the Site and  are not responsible for any offensive, inappropriate, obscene, unlawful  or otherwise objectionable content you may encounter on the Site or in  connection with any User Content or Third Party Content. The Company is  not responsible for the conduct, whether online or offline, of any User  of the Site or Service. <br />
        <br />
      The Site and the Service may be temporarily unavailable from time to  time for maintenance or other reasons. Company assumes no  responsibility for any error, omission, interruption, deletion, defect,  delay in operation or transmission, communications line failure, theft  or destruction or unauthorized access to, or alteration of, User  communications. The Company is not responsible for any problems or  technical malfunction of any telephone network or lines, computer  online systems, servers or providers, computer equipment, software,  failure of email or players on account of technical problems or traffic  congestion on the Internet or at any Site or combination thereof,  including injury or damage to Users or to any other person's computer  related to or resulting from participating or downloading materials in  connection with the Web and/or in connection with the Service. Under no  circumstances will the Company be responsible for any loss or damage,  including any loss or damage to any User Content or personal injury or  death, resulting from anyone's use of the Site or the Service, any User  Content or Third Party Content posted on or through the Site or the  Service or transmitted to Users, or any interactions between Users of  the Site, whether online or offline. <br />
      <br />
      THE SITE, THE SERVICE AND THE SITE CONTENT ARE PROVIDED &quot;AS-IS&quot; AND THE  COMPANY DISCLAIMS ANY AND ALL REPRESENTATIONS AND WARRANTIES, WHETHER  EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION IMPLIED WARRANTIES OF  TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR  NON-INFRINGEMENT. THE COMPANY CANNOT GUARANTEE AND DOES NOT PROMISE ANY  SPECIFIC RESULTS FROM USE OF THE SITE AND/OR THE SERVICE. COMPANY DOES  NOT REPRESENT OR WARRANT THAT CONTENT OR MATERIALS ON THE SITE ARE  ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE OR THAT THE SITE OR  ITS SERVERS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. THEREFORE,  YOU SHOULD EXERCISE CAUTION IN THE USE AND DOWNLOADING OF ANY SUCH  CONTENT OR MATERIALS AND USE INDUSTRY-RECOGNIZED SOFTWARE TO DETECT AND  DISINFECT VIRUSES. <br />
      <br />
      Company reserves the right to change any and all content contained  in the Site and any Services offered through the Site at any time  without notice. Reference to any products, services, processes or other  information, by trade name, trademark, manufacturer, supplier or  otherwise does not constitute or imply endorsement, sponsorship or  recommendation thereof, or any affiliation therewith, by Company. </p>
    <h2>Limitation on Liability</h2>
    <p>EXCEPT IN JURISDICTIONS WHERE  SUCH PROVISIONS ARE RESTRICTED, IN NO EVENT WILL COMPANY OR ITS  DIRECTORS, EMPLOYEES OR AGENTS BE LIABLE TO YOU OR ANY THIRD PERSON FOR  ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE  DAMAGES, INCLUDING FOR ANY LOST PROFITS OR LOST DATA ARISING FROM YOUR  USE OF THE SITE OR THE SERVICE OR ANY OF THE SITE CONTENT OR OTHER  MATERIALS ON OR ACCESSED THROUGH THE SITE, EVEN IF THE COMPANY IS AWARE  OR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING  ANYTHING TO THE CONTRARY CONTAINED HEREIN, THE COMPANY'S LIABILITY TO  YOU FOR ANY CAUSE WHATSOEVER, AND REGARDLESS OF THE FORM OF THE ACTION,  WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO  COMPANY FOR THE SERVICE DURING THE TERM OF MEMBERSHIP, BUT IN NO CASE  WILL THE COMPANY'S LIABILITY TO YOU EXCEED $1000. YOU ACKNOWLEDGE THAT  IF NO FEES ARE PAID TO COMPANY FOR THE SERVICE, YOU SHALL BE LIMITED TO  INJUNCTIVE RELIEF ONLY, UNLESS OTHERWISE PERMITTED BY LAW, AND SHALL  NOT BE ENTITLED TO DAMAGES OF ANY KIND FROM COMPANY, REGARDLESS OF THE  CAUSE OF ACTION. <br />
        <br />
      CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR  THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO  YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS OR LIMITATIONS  MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS. </p>
    <h2>Governing Law; Venue and Jurisdiction</h2>
    <p>By visiting or  using the Site and/or the Service, you agree that the laws of the State  of Delaware, without regard to principles of conflict of laws, will  govern these Terms of Use and any dispute of any sort that might arise  between you and the Company or any of our affiliates. With respect to  any disputes or claims not subject to arbitration (as set forth below),  you agree not to commence or prosecute any action in connection  therewith other than in the state and federal courts of California, and  you hereby consent to, and waive all defenses of lack of personal  jurisdiction and forum non conveniens with respect to, venue and  jurisdiction in the state and federal courts of California.</p>
    <h2>Arbitration</h2>
    <p>YOU  AND COMPANY AGREE THAT THE SOLE AND EXCLUSIVE FORUM AND REMEDY FOR ANY  AND ALL DISPUTES AND CLAIMS RELATING IN ANY WAY TO OR ARISING OUT OF  THESE SITE TERMS, THE SITE AND/OR THE SERVICE (INCLUDING YOUR VISIT TO  OR USE OF THE SITE AND/OR THE SERVICE) SHALL BE FINAL AND BINDING  ARBITRATION, except that, to the extent that either of us has in any  manner infringed upon or violated or threatened to infringe upon or  violate the other party's patent, copyright, trademark or trade secret  rights, such other party may seek injunctive or other appropriate  relief. <br />
        <br />
      Arbitration under this Agreement shall be conducted by the American  Arbitration Association (the &quot;AAA&quot;) under its Commercial Arbitration  Rules and, in the case of consumer disputes, the AAA's Supplementary  Procedures for Consumer Related Disputes ( the &quot;AAA Consumer Rules&quot;)  (collectively the &quot;AAA Rules&quot;). The location of the arbitration and the  allocation of costs and fees for such arbitration shall be determined  in accordance with such AAA Rules and shall be subject to the  limitations provided for in the AAA Consumer Rules (for consumer  disputes). If such costs are determined to be excessive in a consumer  dispute, the Company will be responsible for paying all arbitration  fees and arbitrator compensation in excess of what is deemed  reasonable. The arbitrator's award shall be binding and may be entered  as a judgment in any court of competent jurisdiction. <br />
      <br />
      To the fullest extent permitted by applicable law, NO ARBITRATION OR  CLAIM UNDER THESE TERMS OF USE SHALL BE JOINED TO ANY OTHER ARBITRATION  OR CLAIM, INCLUDING ANY ARBITRATION OR CLAIM INVOLVING ANY OTHER  CURRENT OR FORMER USER OF THE SERVICE, AND NO CLASS ARBITRATION  PROCEEDINGS SHALL BE PERMITTED. In no event shall any claim, action or  proceeding by you related in any way to the Site and/or the Service  (including your visit to or use of the Site and/or the Service) be  instituted more than three (3) year after the cause of action arose.</p>
    <h2>Indemnity</h2>
    <p>You  agree to indemnify and hold the Company, its subsidiaries and  affiliates, and each of their directors, officers, agents, contractors,  partners and employees, harmless from and against any loss, liability,  claim, demand, damages, costs and expenses, including reasonable  attorney's fees, arising out of or in connection with any User Content,  any Third Party Content you post or share on or through the Site  (including without limitation through the Share Service), your use of  the Service or the Site, your conduct in connection with the Service or  the Site or with other Users of the Service or the Site, or any  violation of this Agreement or of any law or the rights of any third  party. </p>
    <h2>Submissions</h2>
    <p>You acknowledge and agree that any  questions, comments, suggestions, ideas, feedback or other information  about the Site or the Service (&quot;Submissions&quot;), provided by you to  Company are non-confidential and shall become the sole property of  Company. Company shall own exclusive rights, including all intellectual  property rights, and shall be entitled to the unrestricted use and  dissemination of these Submissions for any purpose, commercial or  otherwise, without acknowledgment or compensation to you.</p>
    <h2>Other</h2>
    <p>These  Terms of Use constitute the entire agreement between you and Company  regarding the use of the Site and/or the Service, superseding any prior  agreements between you and Company relating to your use of the Site or  the Service. The failure of Company to exercise or enforce any right or  provision of these Terms of Use shall not constitute a waiver of such  right or provision in that or any other instance. If any provision of  this Agreement is held invalid, the remainder of this Agreement shall  continue in full force and effect. If any provision of these Site Terms  shall be deemed unlawful, void or for any reason unenforceable, then  that provision shall be deemed severable from these Terms of Use and  shall not affect the validity and enforceability of any remaining  provisions. </p>
    <h2>Questions</h2>
    <p>Please visit our <a href="http://www.facebook.com/help.php">Help</a> page for more information.</p>
  </div>
</div>
</body>
</html>
